version: '3'
services:
  pepeaspnet_centralizador:
    build: ASPNET_Centralizador/
    ports:
    - "8087:80"
    - "8088:443"
    environment:
      ASPNETCORE_URLS: "https://+;http://+"
      ASPNETCORE_HTTPS_PORT: "8088"
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
    - ${APPDATA}\Microsoft\UserSecrets\:/root/.microsoft/usersecrets
    - ${USERPROFILE}\.aspnet\https:/root/.aspnet/https/